### ISSUE TITLE
Correctness and performance issues for iteration

### ISSUE THREAD

**Issue by andreasnoack** [quinnj/WeakRefStrings.jl#19]
These were discussed in https://github.com/quinnj/WeakRefStrings.jl/commit/00e1ed8a71ee7c8db0e01701d8d6ee3b42a3b52f#commitcomment-25076766 but should be tracked in an issue to be more visible.

#### `next` assumes that all characters are encoded with the same number of code units
```julia
julia> s
"Rød grød med fløde"

julia> ws
"Rød grød med fløde"

julia> String([c for c in s])
"Rød grød med fløde"

julia> String([c for c in ws])
"RÃ¸d grÃ¸d med flÃ"
```

#### `endof` is `O(n)` because it converts to `String`
```julia
julia> @btime endof(s);
  19.281 ns (0 allocations: 0 bytes)

julia> @btime endof(ws);
  40.133 ns (1 allocation: 48 bytes)
```

l think we should be a bit reluctant about using `WeakRefStrings` in the data stack until these issues are fixed. The package would probably have to reimplement much of the functionality in base to fix these issues.

**Comment by quinnj** [comment]
Alright, having noodled on this for a while, I've come to the conclusion that WeakRefStrings shouldn't be used for any kind of string processing. They started out, and will continue to be for the moment, a tool for optimizing IO by delaying `String` materialization until the user actually needs it. As such, it can be considered in terms of a "data item" or "atom" (i.e. are two WKRStrings equal? conversions to-from String), but no actual string processing functions are implemented directly on them (including `length`, `endof`, iteration, etc.). 

In the future, we could certainly work thru the non-trivial process of defining proper string interface methods on WeakRefString directly, but for now, I'm doing the work to ensure that end users never actually see WeakRefStrings and will help package developers who'd still like to utilize WeakRefStrings to do so properly.

This plan is fully implemented in #21
