### ISSUE TITLE
Is there a notion of "valid" for WeakRefStrings?

### ISSUE THREAD

**Issue by tcovert** [quinnj/WeakRefStrings.jl#3]
I am trying to convert a messy column of WeakRefStrings to utf8 or ascii, and I am fine throwing away strings that are not valid in one of the traditional string types.  Is there a way to test for validity in one of these types?  If not, is there another way to convert a WeakRefString to utf8/ascii, aside from using string(), which will throw a UnicodeError if the string is not valid.  I suppose I could do a try/catch, but I was wondering if there was a less messy way.

**Comment by quinnj** [comment]
Currently there's [isvalid](http://docs.julialang.org/en/latest/stdlib/strings/#Base.isvalid) in Base. I would probably do something like
```julia
isvalid(str) ? string(str) : ""
```

**Comment by tcovert** [comment]
unfortunately, 'unsafe_wrap()' doesn't appear to be in Julia 0.4.6.  does there exist a 0.4 version of this statement?

**Comment by quinnj** [comment]
`pointer_to_array(str.ptr, str.len)`

**Comment by tcovert** [comment]
thanks that did it!

**Comment by tcovert** [comment]
Also, for the record, I see that you added unsafe_wrap() for 0.4 users in CSV.jl.

**Comment by tcovert** [comment]
Any suggestions for what a user ought to do if unsafe_wrap() does crash on a string when I attempt to test for UTF8 validity?  My test is:

`isvalid(UTF8String, CSV.unsafe_wrap(Array, x.ptr, x.len))`

where x is a WeakRefString
