### ISSUE TITLE
note unsafe_wrap for ASCII/UTF-8

### ISSUE THREAD

**Issue by stevengj** [quinnj/WeakRefStrings.jl#4]
Is this package useful for ASCII/UTF-8 data, given the `unsafe_wrap(String, ...)` function in Base?   If not, maybe a note in the README?

**Comment by quinnj** [comment]
Yes, in my performance tests, `unsafe_wrap` is still magnitudes slower than creating a `WeakRefString`, due, I believe, to all the overhead from Array creation. I can try to dig up the benchmarks.

**Comment by stevengj** [comment]
Ah, okay; could be good to mention this in the README.
