### ISSUE TITLE
Is the StrongRefString equiv of this just Base.SubString?

### ISSUE THREAD

**Issue by oxinabox** [quinnj/WeakRefStrings.jl#7]
Am I understanding correctly that the primary difference between a `WeakRefString`, and a` SubString`,
is that a `SubString` holds a strong reference to the original String,
so that as long as the` SubString` remains in scope, the original String will never be garbage collected?

When should one choose a  `WeakRefString`, over a ` SubString`, and visaversa ?

**Comment by quinnj** [comment]
Your understanding is correct.

Currently, WeakRefStrings can be stack allocated and Substrings cannot due to the reference to the original string. There's been talk of fixing this for 1.0, but until then, WeakRefStrings are much more performance.

**Comment by oxinabox** [comment]
Ah I understand.
On that basis have you considered defining a method `split(::Type{WeakRefString}, string; kwargs...)`,
and maybe a few of the other methods that commonly produce Substrings?

**Comment by quinnj** [comment]
I haven't personally had a need for something like, but I'd be open to PRs implementing them. Honestly I haven't planned on this being a long-term package due precisely to the planned improvements in Base, but it's also not entirely clear when those enhancements will land.
